version: '3.7'

services:
  web:
    build: ./app1
    command:  python manage.py collectstatic
    command: gunicorn hello.wsgi:application --bind 0.0.0.0:8000
   # volumes:
    #  - static_volume:/home/ubuntu/app/app1/static
    ports:
      - 8000:8000
  
  nginx:
    build: ./nginx
   # volumes:
    #  - static_volume:/home/ubuntu/app/app1/static
    ports:
      - 1337:80
    depends_on:
      - web
  #volumes:
    # static_volume:
